Repository NeuraLegion/sectester-js, pull requests merged in 2022-04, with the labels that each got.

#16 ci: upload coverage report on push and pull_request
  .github/workflows/auto-build.yml
  .github/workflows/coverage.yml
Labels: Type: tooling

#12 feat(core): provide message abstractions
  package-lock.json
  package.json
  packages/core/README.md
  packages/core/src/bus/Command.spec.ts
  packages/core/src/bus/Command.ts
  packages/core/src/bus/CommandDispatcher.ts
  packages/core/src/bus/Event.spec.ts
  packages/core/src/bus/Event.ts
  packages/core/src/bus/EventBus.ts
  packages/core/src/bus/EventDispatcher.ts
  packages/core/src/bus/EventHandler.ts
  packages/core/src/bus/Message.spec.ts
  packages/core/src/bus/Message.ts
  packages/core/src/bus/RetryStartegy.ts
  packages/core/src/bus/decorators/bind.ts
  packages/core/src/bus/decorators/index.ts
  packages/core/src/bus/exceptions/EventHandlerNotFound.ts
  packages/core/src/bus/exceptions/IllegalOperation.ts
  packages/core/src/bus/exceptions/NoResponse.ts
  packages/core/src/bus/exceptions/NoSubscriptionsFound.ts
  packages/core/src/bus/exceptions/index.ts
  packages/core/src/bus/index.ts
  packages/core/src/index.ts
  packages/core/src/utils/get-type-name.spec.ts
  packages/core/src/utils/get-type-name.ts
  packages/core/src/utils/index.ts
Labels: Type: enhancement

#18 fix(core): introduce a constructor types to resolve compile-time errors
  packages/core/src/bus/Event.ts
  packages/core/src/bus/EventBus.ts
  packages/core/src/bus/EventHandler.ts
  packages/core/src/bus/decorators/bind.spec.ts
  packages/core/src/bus/decorators/bind.ts
  packages/core/src/credentials-provider/EnvCredentialProvider.spec.ts
  packages/core/src/utils/first.spec.ts
Labels: Type: bug

#6 feat(bus): implement `EventBus` for `RabbitMQ`
  package-lock.json
  package.json
  packages/bus/.babelrc
  packages/bus/.eslintrc.json
  packages/bus/README.md
  packages/bus/jest.config.js
  packages/bus/package.json
  packages/bus/project.json
  packages/bus/src/brokers/RMQEventBus.spec.ts
  packages/bus/src/brokers/RMQEventBus.ts
  packages/bus/src/brokers/RMQEventBusConfig.ts
  packages/bus/src/brokers/index.ts
  packages/bus/src/index.ts
  packages/bus/tsconfig.json
  packages/bus/tsconfig.lib.json
  packages/bus/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: Type: enhancement

#14 feat(bus): implement exponential backoff retry strategy
  package-lock.json
  packages/bus/README.md
  packages/bus/package.json
  packages/bus/src/brokers/RMQEventBus.spec.ts
  packages/bus/src/brokers/RMQEventBus.ts
  packages/bus/src/index.ts
  packages/bus/src/retry-strategies/ExponentialBackoffRetryStrategy.spec.ts
  packages/bus/src/retry-strategies/ExponentialBackoffRetryStrategy.ts
  packages/bus/src/retry-strategies/index.ts
  packages/bus/src/utils/delay.ts
  packages/bus/src/utils/index.ts
Labels: Type: enhancement

#23 refactor(bus): rename HTTP command and its dispatcher
  packages/bus/src/commands/HttpRequest.spec.ts
  packages/bus/src/commands/HttpRequest.ts
  packages/bus/src/commands/index.ts
  packages/bus/src/dispatchers/AxiosCommandDispatcherConfig.ts
  packages/bus/src/dispatchers/HttpCommandDispatcher.spec.ts
  packages/bus/src/dispatchers/HttpCommandDispatcher.ts
  packages/bus/src/dispatchers/HttpCommandDispatcherConfig.ts
  packages/bus/src/dispatchers/index.ts
Labels: Type: refactoring

#26 fix(bus): decrease RPS value
  packages/bus/src/dispatchers/HttpCommandDispatcher.ts
Labels: Type: bug

#27 refactor(bus): introduce the assertion method to retrieve a channel
  packages/bus/src/dispatchers/RMQEventBus.ts
Labels: Type: technical debt, Type: refactoring

#29 refactor(bus): break down `buildOptions` into small methods
  packages/bus/src/dispatchers/RMQEventBus.ts
Labels: Type: technical debt, Type: refactoring

#33 refactor(bus): extract a common logic from `register` and `unregister` methods
  packages/bus/src/dispatchers/RMQEventBus.ts
Labels: Type: technical debt, Type: refactoring

#32 feat(core): allow using a string and symbol with `@bind`
  packages/bus/src/dispatchers/RMQEventBus.ts
  packages/core/README.md
  packages/core/src/bus/decorators/bind.spec.ts
  packages/core/src/bus/decorators/bind.ts
  packages/core/src/bus/exceptions/UnsupportedEventType.ts
  packages/core/src/bus/exceptions/index.ts
Labels: Type: enhancement

#24 docs(bus): improve `HttpComandDispatcher` description
  packages/bus/README.md
Labels: Type: documentation
