Repository NeuraLegion/sectester-js, pull requests merged in 2025-04, with the labels that each got.

#245 fix(reporter): proper resolve test file paths when using nodejs test runner
  packages/reporter/src/reporters/github/GitHubCheckRunReporter.ts
Labels: Type: bug

#247 feat(scan): add authentication support
  packages/scan/README.md
  packages/scan/src/DefaultDiscoveries.ts
  packages/scan/src/target/Target.ts
Labels: Type: enhancement

#248 fix(scan): increase request timeout for EP creation
  packages/scan/src/DefaultDiscoveries.spec.ts
  packages/scan/src/DefaultDiscoveries.ts
Labels: Type: bug

#249 docs(readme): add missing Bright API key scope
  README.md
Labels: Type: documentation
