Repository NeuraLegion/sectester-js, pull requests merged in 2025-03, with the labels that each got.

#234 refactor(repeater): use the native MIME parser
  packages/repeater/package.json
  packages/repeater/src/request-runner/HttpRequestRunner.spec.ts
  packages/repeater/src/request-runner/HttpRequestRunner.ts
  packages/repeater/src/request-runner/index.ts
  packages/repeater/src/request-runner/protocols/index.ts
Labels: Type: refactoring

#236 docs(README): update API key instructions for clarity
  README.md
Labels: Type: documentation

#235 feat(scan): simplify and streamline Target interface
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/utils/check-boundaries.ts
  packages/core/src/utils/index.ts
  packages/core/src/utils/types.spec.ts
  packages/core/src/utils/types.ts
  packages/runner/src/lib/SecScan.ts
  packages/scan/README.md
  packages/scan/src/DefaultDiscoveries.spec.ts
  packages/scan/src/DefaultDiscoveries.ts
  packages/scan/src/DefaultScans.ts
  packages/scan/src/Scans.ts
  packages/scan/src/target/Body.spec.ts
  packages/scan/src/target/Body.ts
  packages/scan/src/target/HeadersType.ts
  packages/scan/src/target/QueryParamsType.ts
  packages/scan/src/target/Target.spec.ts
  packages/scan/src/target/Target.ts
  packages/scan/src/target/body-parsers/BinaryBodyParser.spec.ts
  packages/scan/src/target/body-parsers/BinaryBodyParser.ts
  packages/scan/src/target/body-parsers/BodyParser.ts
  packages/scan/src/target/body-parsers/FormDataBodyParser.spec.ts
  packages/scan/src/target/body-parsers/FormDataBodyParser.ts
  packages/scan/src/target/body-parsers/JsonBodyParser.spec.ts
  packages/scan/src/target/body-parsers/JsonBodyParser.ts
  packages/scan/src/target/body-parsers/TextBodyParser.spec.ts
  packages/scan/src/target/body-parsers/TextBodyParser.ts
  packages/scan/src/target/body-parsers/UrlEncodedBodyParser.spec.ts
  packages/scan/src/target/body-parsers/UrlEncodedBodyParser.ts
  packages/scan/src/target/body-parsers/index.ts
  packages/scan/src/target/body-parsers/register.ts
  packages/scan/src/target/index.ts
  packages/scan/src/utils/entries-to-list.spec.ts
  packages/scan/src/utils/entries-to-list.ts
  packages/scan/src/utils/index.ts
Labels: Type: enhancement

#238 fix(core): register Projects provider
  packages/core/src/register.ts
  packages/repeater/src/lib/RepeaterFactory.spec.ts
  packages/runner/src/lib/SecRunner.spec.ts
  packages/runner/src/lib/SecRunner.ts
Labels: Type: bug

#239 feat(scan): resolve target parameters automatically
  packages/scan/src/ScanSettings.spec.ts
  packages/scan/src/ScanSettings.ts
  packages/scan/src/target/Target.spec.ts
  packages/scan/src/target/Target.ts
Labels: Type: enhancement

#241 feat(scan): test ids as strings
  packages/runner/README.md
  packages/runner/src/lib/SecRunner.spec.ts
  packages/runner/src/lib/SecScan.spec.ts
  packages/scan/README.md
  packages/scan/src/DefaultScans.spec.ts
  packages/scan/src/ScanFactory.spec.ts
  packages/scan/src/ScanSettings.spec.ts
  packages/scan/src/ScanSettings.ts
  packages/scan/src/models/ScanConfig.ts
  packages/scan/src/models/TestType.ts
  packages/scan/src/models/index.ts
Labels: Type: enhancement

#243 feat(core): make `app.brightsec.com` default hostname value
  LICENSE
  README.md
  packages/core/README.md
  packages/core/src/configuration/Configuration.spec.ts
  packages/core/src/configuration/Configuration.ts
  packages/repeater/README.md
  packages/reporter/README.md
  packages/reporter/src/__fixtures__/issues.ts
  packages/reporter/src/reporters/github/GitHubCheckRunReporter.spec.ts
  packages/reporter/src/reporters/github/builders/MultiItemsPayloadBuilder.spec.ts
  packages/reporter/src/reporters/github/builders/SingleItemPayloadBuilder.spec.ts
  packages/runner/README.md
  packages/scan/src/Scan.spec.ts
Labels: Type: enhancement
